export const captionPool = [
  "Chewing gum stuck to the bottom of a table",
  "A man playing an umbrella as if it was a guitar",
  "A spider from mars",
  "An awkward waiting room",
  "Excellent timing",
  "Your vegetable friend",
  "Brushing your tongue",
  "A very disappointing Christmas",
  "Forgetting how to eat",
  "Eating spiderwebs",
  "Darth Vader at his day job",
  "Making an onion cry",
  "An Aztec sacrifice",
  "A man hiding in a pram",
  "A centaur lollipop man",
  "An exploding cuckoo clock",
  "Eye-wateringly strong pickles",
  "A staring contest",
  "Licking people's shoes",
  "Abducted by butterflies",
  "What really happened to the dinosaurs",
  "Seeing a man about a horse",
  "Combing your hair with a hedgehog",
  "Frisbee decapitation",
  "Giraffe limbo contest",
];
