export const captionPool = [
  "Chewing gum stuck to the bottom of a table",
  "A man playing an umbrella as if it was a guitar",
  "A spider from mars",
  "An awkward waiting room",
  "Excellent timing",
  "Your vegetable friend",
  "Brushing your tongue",
  "A very disappointing Christmas",
  "Forgetting how to eat",
  "Eating spiderwebs",
  "Darth Vader at his day job",
  "Making an onion cry",
  "An Aztec sacrifice",
  "A man hiding in a pram",
  "A centaur lollipop man",
  "An exploding cuckoo clock",
  "Eye-wateringly strong pickles",
  "A staring contest",
  "Licking people's shoes",
  "Abducted by butterflies",
  "What really happened to the dinosaurs",
  "Seeing a man about a horse",
  "Combing your hair with a hedgehog",
  "Frisbee decapitation",
  "Giraffe limbo contest",
  "Biting off more than you can chew",
  "Polishing a turd",
  "Cleaning your pipes",
  "Cereal killer",
  "Freezing your own head",
  "A T-Rex with a brand new handbag",
  "Mittens on a kitten",
  "More melons than you can carry",
  "Deflating an elephant",
  "Bottle-feeding a pig",
  "A supermodel with hobbit feet",
  "Angry potatoes meeting",
  "Bodybuilding toast",
  "Marrying a tiger",
  "The octopus who's late to the party",
  "A baby orchestra",
  "A train flying over a rainbow",
  "A lighthouse on fire",
  "Making your teddy bears fight to the death",
  "Broccoli ice cream",
  "Playing chess in a thunderstorm",
  "Accidentally stapling your hand to a cat",
  "Wind blowing someone over",
  "The Monkey King",
  "Choo, choo!",
  "Snapping a TV in half with your bare hands",
  "A leopard struggling to do its taxes",
  "Getting lost in a furniture shop",
  "Explaining knock-knock jokes to a parrot",
  "Sad Robocop",
  "Brian Blessed riding into battle",
  "A squirrel knitting",
  "A seal posting a letter",
  "A cucumber brushing its hair",
  "Happy Potter being breatalyzed by the police",
  "A woman trying to buy a tortoise",
  "A software engineer learning Javascript",
  "A banana playing monopoly",
  "Running away from your fears",
  "A car boot sale full of frogs",
  "Wearing your hair in a towel",
  "Running with scissors",
  "Camping in space",
  "A ghost playing Operation",
  "Iron Man doing the ironing",
  "afternoon tea with the queen",
  "Finding wally in wheres wally",
  "Making mashed potato",
  "A snake trying to climb a tree",
  "Eating your own foot",
  "I hate the green flashing light",
  "Hello. I have the urge to kill",
  "Oh no! You’re going to speak again, aren’t you?",
  "Rubber ducks are planning world domination!",
  "But my tree only hit the car in self-defence!",
  "I know kung fu",
  "Did my sarcasm hurt your feels? Get over it.",
  "Fat kids are harder to kidnap",
  "Don’t mess with me! I have a stick!",
  "Ha ha! I don’t get it",
  "I am pretending to be a tomato",
  "Never set yourself on fire",
  "The banana has legs!",
  "Banana suicide!",
  "Back off! The ice cream is mine!",
  "I am here to install your cushion",
  "Your hands are really hairy",
  "Tomatoes are depressing",
  "My eyebrow died",
];
