export const captionPool = [
  "Chewing gum stuck to the bottom of a table",
  "A man playing an umbrella as if it was a guitar",
  "A spider from mars",
  "An awkward waiting room",
  "Excellent timing",
  "Your vegetable friend",
  "Brushing your tongue",
  "A very disappointing Christmas",
  "Forgetting how to eat",
  "Eating spiderwebs",
  "Darth Vader at his day job",
  "Making an onion cry",
  "An Aztec sacrifice",
  "A man hiding in a pram",
  "A centaur lollipop man",
  "An exploding cuckoo clock",
  "Eye-wateringly strong pickles",
  "A staring contest",
  "Licking people's shoes",
  "Abducted by butterflies",
  "What really happened to the dinosaurs",
  "Seeing a man about a horse",
  "Combing your hair with a hedgehog",
  "Frisbee decapitation",
  "Giraffe limbo contest",
  "Biting off more than you can chew",
  "Polishing a turd",
  "Cleaning your pipes",
  "Cereal killer",
  "Freezing your own head",
  "A T-Rex with a brand new handbag",
  "1950s sex education",
  "Mittens on a kitten",
  "More melons than you can carry",
  "Deflating an elephant",
  "Bottle-feeding a pig",
  "A supermodel with hobbit feet",
  "Angry potatoes meeting",
  "Bodybuilding toast",
  "Marrying a tiger",
  "The octopus who's late to the party",
  "A baby orchestra",
];
